import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin-auth";

function Evidence({ label, url }: { label: string; url: string | null }) { return <div><p className="mb-2 text-sm font-medium">{label}</p>{url ? <a href={url} target="_blank" rel="noreferrer">{/* Evidence URLs are dynamic Supabase Storage objects. */}{/* eslint-disable-next-line @next/next/no-img-element */}<img src={url} alt={label} className="aspect-[4/3] w-full border border-stone-300 object-cover" /></a> : <div className="grid aspect-[4/3] place-items-center border border-dashed border-stone-300 bg-stone-50 text-sm text-stone-500">Not submitted</div>}</div>; }
export default async function TransactionDetail({ params }: { params: { id: string } }) {
  const { client } = await requireAdmin();
  const [{ data: transaction }, { data: messages }] = await Promise.all([client.from("transactions").select("*, merchants(business_name, merchant_id), listings(title, listing_id)").eq("id", params.id).maybeSingle(), client.from("messages").select("*").eq("transaction_id", params.id).order("created_at", { ascending: true })]);
  if (!transaction) notFound();
  const merchant = Array.isArray(transaction.merchants) ? transaction.merchants[0] : transaction.merchants;
  const listing = Array.isArray(transaction.listings) ? transaction.listings[0] : transaction.listings;
  return <><Link href="/admin/transactions" className="text-sm font-semibold text-emerald-800">&larr; Transactions</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4 border border-stone-300 bg-white p-6"><div><p className="font-mono text-xs text-stone-500">{transaction.transaction_id}</p><h1 className="mt-1 text-3xl font-semibold">{listing?.title ?? "Transaction"}</h1><p className="mt-2 text-sm text-stone-600">{merchant?.business_name ?? "Unknown merchant"} &middot; {transaction.buyer_whatsapp_number}</p></div><span className="border border-stone-300 px-3 py-1 text-sm font-semibold capitalize">{transaction.status.replaceAll("_", " ")}</span></div><div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="border border-stone-300 bg-white p-5"><h2 className="font-semibold">Payment and review</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-stone-500">Amount</dt><dd className="mt-1 font-semibold">R{(transaction.amount_cents / 100).toFixed(2)}</dd></div><div><dt className="text-stone-500">PayFast reference</dt><dd className="mt-1 font-mono text-xs">{transaction.payfast_pf_payment_id ?? transaction.payfast_payment_id ?? "Pending"}</dd></div><div><dt className="text-stone-500">AI match confidence</dt><dd className="mt-1">{transaction.ai_match_confidence === null ? "Not assessed" : `${Math.round(Number(transaction.ai_match_confidence) * 100)}%`}</dd></div><div><dt className="text-stone-500">Created</dt><dd className="mt-1">{new Date(transaction.created_at).toLocaleString()}</dd></div></dl>{transaction.ai_match_notes && <p className="mt-5 border-l-2 border-emerald-700 pl-3 text-sm text-stone-600">{transaction.ai_match_notes}</p>}</section><section className="border border-stone-300 bg-white p-5"><h2 className="font-semibold">Evidence photos</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Evidence label="Seller fulfilment" url={transaction.seller_evidence_url} /><Evidence label="Buyer receipt" url={transaction.buyer_evidence_url} /></div></section></div><section className="mt-7 border border-stone-300 bg-white p-5"><h2 className="font-semibold">Chat log</h2><div className="mt-5 space-y-3">{(messages ?? []).map((message) => <div key={message.id} className={`max-w-[85%] border p-3 text-sm ${message.direction === "outbound" ? "ml-auto border-emerald-200 bg-emerald-50" : "border-stone-200 bg-stone-50"}`}><p className="mb-1 text-xs font-semibold uppercase tracking-wide text-stone-500">{message.direction} &middot; {message.message_type}</p>{message.body && <p>{message.body}</p>}{message.media_url && <a className="text-emerald-800 underline" href={message.media_url} target="_blank" rel="noreferrer">Open media</a>}<p className="mt-2 text-xs text-stone-400">{new Date(message.created_at).toLocaleString()}</p></div>)}{!messages?.length && <p className="text-sm text-stone-500">No messages logged for this transaction.</p>}</div></section></>;
}