import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin-auth";

export default async function MerchantDetail({ params }: { params: { id: string } }) {
  const { client } = await requireAdmin();
  const [{ data: merchant }, { data: listings }, { data: transactions }] = await Promise.all([client.from("merchants").select("*").eq("id", params.id).maybeSingle(), client.from("listings").select("*").eq("merchant_id", params.id).order("created_at", { ascending: false }), client.from("transactions").select("*").eq("merchant_id", params.id).order("created_at", { ascending: false })]);
  if (!merchant) notFound();
  return <><Link href="/admin/merchants" className="text-sm font-semibold text-emerald-800">&larr; Merchants</Link><div className="mt-5 border border-stone-300 bg-white p-6"><p className="font-mono text-xs text-stone-500">{merchant.merchant_id}</p><h1 className="mt-1 text-3xl font-semibold">{merchant.business_name}</h1><div className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><p><span className="block text-stone-500">WhatsApp</span>{merchant.whatsapp_number}</p><p><span className="block text-stone-500">Status</span><span className="capitalize">{merchant.status}</span></p><p><span className="block text-stone-500">Trust score</span>{Number(merchant.trust_score).toFixed(2)}</p></div></div><section className="mt-7"><h2 className="text-xl font-semibold">Listings</h2><div className="mt-3 overflow-x-auto border border-stone-300 bg-white"><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-b border-stone-300 bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="px-4 py-3">Listing</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Created</th></tr></thead><tbody>{(listings ?? []).map((listing) => <tr key={listing.id} className="border-b border-stone-200"><td className="px-4 py-3"><span className="font-semibold">{listing.title}</span><p className="font-mono text-xs text-stone-500">{listing.listing_id}</p></td><td className="px-4 py-3">R{(listing.price_cents / 100).toFixed(2)}</td><td className="px-4 py-3 capitalize">{listing.status}</td><td className="px-4 py-3 text-stone-500">{new Date(listing.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></section><section className="mt-7"><h2 className="text-xl font-semibold">Transaction history</h2><div className="mt-3 border border-stone-300 bg-white">{(transactions ?? []).map((transaction) => <Link key={transaction.id} href={`/admin/transactions/${transaction.id}`} className="flex items-center justify-between border-b border-stone-200 p-4 last:border-0 hover:bg-stone-50"><span><strong>{transaction.transaction_id}</strong><span className="ml-3 text-sm text-stone-500">{transaction.buyer_whatsapp_number}</span></span><span className="text-sm capitalize">{transaction.status}</span></Link>)}{!transactions?.length && <p className="p-5 text-sm text-stone-500">No transactions yet.</p>}</div></section></>;
}