import Link from "next/link";
import { requireAdmin } from "@/lib/admin-auth";

const statuses = ["pending_payment", "awaiting_fulfilment", "awaiting_buyer_confirmation", "released", "disputed", "refunded", "cancelled"];
export default async function TransactionsPage({ searchParams }: { searchParams: { status?: string } }) {
  const { client } = await requireAdmin();
  let query = client.from("transactions").select("*, merchants(business_name)").order("created_at", { ascending: false });
  if (searchParams.status && statuses.includes(searchParams.status)) query = query.eq("status", searchParams.status);
  const { data: transactions } = await query;
  return <><p className="text-xs font-semibold uppercase tracking-[0.15em] text-emerald-700">Payment ledger</p><h1 className="mt-1 text-3xl font-semibold">Transactions</h1><div className="mt-5 flex flex-wrap gap-2">{["all", ...statuses].map((status) => <Link key={status} href={status === "all" ? "/admin/transactions" : `/admin/transactions?status=${status}`} className={`border px-3 py-1.5 text-xs font-semibold capitalize ${(!searchParams.status && status === "all") || searchParams.status === status ? "border-emerald-800 bg-emerald-800 text-white" : "border-stone-300 bg-white text-stone-600"}`}>{status.replaceAll("_", " ")}</Link>)}</div><div className="mt-5 overflow-x-auto border border-stone-300 bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-stone-300 bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="px-4 py-3">Transaction</th><th className="px-4 py-3">Merchant</th><th className="px-4 py-3">Buyer</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Created</th></tr></thead><tbody>{(transactions ?? []).map((transaction) => <tr key={transaction.id} className="border-b border-stone-200 hover:bg-stone-50"><td className="px-4 py-3"><Link href={`/admin/transactions/${transaction.id}`} className="font-mono font-semibold text-emerald-800">{transaction.transaction_id}</Link></td><td className="px-4 py-3">{(Array.isArray(transaction.merchants) ? transaction.merchants[0] : transaction.merchants)?.business_name ?? "-"}</td><td className="px-4 py-3 font-mono text-xs">{transaction.buyer_whatsapp_number}</td><td className="px-4 py-3">R{(transaction.amount_cents / 100).toFixed(2)}</td><td className="px-4 py-3 capitalize">{transaction.status.replaceAll("_", " ")}</td><td className="px-4 py-3 text-stone-500">{new Date(transaction.created_at).toLocaleDateString()}</td></tr>)}{!transactions?.length && <tr><td colSpan={6} className="px-4 py-12 text-center text-stone-500">No matching transactions.</td></tr>}</tbody></table></div></>;
}