import Link from "next/link";
import { requireAdmin } from "@/lib/admin-auth";
import { resolveDispute } from "@/app/admin/actions";

const priority: Record<string, number> = { open: 0, investigating: 1, resolved_release: 2, resolved_refund: 3 };
export default async function DisputesPage() {
  const { client } = await requireAdmin();
  const { data } = await client.from("disputes").select("*, transactions(transaction_id, amount_cents, buyer_whatsapp_number)").order("created_at", { ascending: false });
  const disputes = [...(data ?? [])].sort((left, right) => priority[left.status] - priority[right.status]);
  return <><p className="text-xs font-semibold uppercase tracking-[0.15em] text-emerald-700">Manual review queue</p><h1 className="mt-1 text-3xl font-semibold">Disputes</h1><div className="mt-7 space-y-4">{disputes.map((dispute) => { const transaction = Array.isArray(dispute.transactions) ? dispute.transactions[0] : dispute.transactions; const resolved = dispute.status.startsWith("resolved_"); return <article key={dispute.id} className="border border-stone-300 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-stone-500">{transaction?.transaction_id ?? "Unknown transaction"}</p><h2 className="mt-1 font-semibold">{dispute.reason}</h2><p className="mt-1 text-sm text-stone-600">{transaction?.buyer_whatsapp_number} &middot; {transaction ? `R${(transaction.amount_cents / 100).toFixed(2)}` : ""}</p></div><span className="border border-stone-300 px-2 py-1 text-xs font-semibold capitalize">{dispute.status.replaceAll("_", " ")}</span></div><Link href={`/admin/transactions/${dispute.transaction_id}`} className="mt-4 inline-block text-sm font-semibold text-emerald-800">Open transaction evidence &rarr;</Link>{resolved ? <p className="mt-4 text-sm text-stone-500">Resolved by {dispute.resolved_by ?? "admin"}{dispute.resolved_at ? ` on ${new Date(dispute.resolved_at).toLocaleString()}` : ""}.</p> : <form action={resolveDispute} className="mt-5 grid gap-3 border-t border-stone-200 pt-5"><input type="hidden" name="disputeId" value={dispute.id} /><input type="hidden" name="transactionId" value={dispute.transaction_id} /><label className="text-sm font-medium">Admin notes<textarea name="adminNotes" defaultValue={dispute.admin_notes ?? ""} rows={2} className="mt-1 block w-full border border-stone-300 p-2 font-normal outline-none focus:border-emerald-700" /></label><div className="flex flex-wrap gap-3"><button name="outcome" value="release" className="bg-emerald-800 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700">Release to merchant</button><button name="outcome" value="refund" className="border border-red-700 px-4 py-2 text-sm font-semibold text-red-800 hover:bg-red-50">Refund buyer</button></div></form>}</article>; })}{!disputes.length && <div className="border border-dashed border-stone-300 bg-white p-12 text-center text-sm text-stone-500">No disputes require review.</div>}</div></>;
}